### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by Weng-Kexin**
- Changed 'log' to 'record (log -> record, loglist -> record)
- simplified boolean in initialModifyCommand
- removed unused import in record.java
- moved Ui.java to ui package 
- added recordType in records (can be entry, limit or debt)
- combined echoAddEntry and echoAddDebts into one method (echoAddRecord)

### CODE REVIEW

**Review by yetong1895 — APPROVED** [review]
great job

**Comment by omupenguin** [comment]
Did you run and check if the tests are working?

**Comment by Weng-Kexin** [comment]
> Did you run and check if the tests are working?

do you mean the entrytest and entrylisttest? i didn't check the test codes but the main code runs fine

**Comment by omupenguin** [comment]
Can just give them a quick run haha.
Anyway there are some conflicts now, need to get them resolved.

**Comment by Weng-Kexin** [comment]
> Can just give them a quick run haha.
> Anyway there are some conflicts now, need to get them resolved.

yep the tests work!

**Review by omupenguin — APPROVED** [review]
Okay, thanks!

**Review by tatayu — APPROVED** [review]

**Pull request merged**
