### PR TITLE
Fix bugs, added exception handling and added Storage Sequence Diagram

### PR DESCRIPTION
**Pull request by yetong1895**
- Fixed the known bugs in redo, undo and sort.
 i.e. sort will not alter the original order of the list.
- Added sort support for limit (amount) and sort amount support for debt and entry.
 i.e. **sort amount**
- Added exception handling for redo, undo and remove.
- Simplify part of the code.
- Moved Ui to ui package.
- Added Storage Sequence Diagram

~~(give up on codacy review)~~

### CODE REVIEW

**Review by tatayu — APPROVED** [review]

**Comment by omupenguin** [comment]
Please add //@@author for easier tracking of work. Also, next time do consider separating the diagrams from the feature to have a better organisation of work.

**Comment by yetong1895** [comment]
> separating the diagrams from the feature

what do you mean by separating the diagrams from the feature?

**Comment by omupenguin** [comment]
What I mean is don't do a PR together. Let's say you created a diagram but it's missing some details, so if any of us wants to edit the diagram, we are unable to because this PR has not been approved yet. And this PR is not approved because the diagram was not finished, but because the feature you are implementing is not complete/has issues. So essentially, our work flow would be bottlenecked here.

**Comment by yetong1895** [comment]
> What I mean is don't do a PR together. Let's say you created a diagram but it's missing some details, so if any of us wants to edit the diagram, we are unable to because this PR has not been approved yet. And this PR is not approved because the diagram was not finished, but because the feature you are implementing is not complete/has issues. So essentially, our work flow would be bottlenecked here.

Okay i see the problem. But everything is fixed 2 day ago and if the PR is not approved or reviewed, every commit i push to my fork will be in this PR. So stuff will eventually stack together. So I think review the PRs ASAP will help in solving any potential issue with the PR and reduce delay in merging with upstream.

**Review by Weng-Kexin — APPROVED** [review]
sorry for reviewing late, i didnt see this pr

**Comment by omupenguin** [comment]
> But everything is fixed 2 day ago and if the PR is not approved or reviewed, every commit i push to my fork will be in this PR. So stuff will eventually stack together. 

Handling multiple branches and having separate PRs will minimize the problem that I'm talking about. I understand that reviewing PRs ASAP is important, but in the case where it isn't approved because there are some things missing, or the checks are failing, it shouldn't be affecting other stuff are actually working by itself. 

Another example is that, if I created 2 commands A and B, and they are not related, ie. they don't require each other to function, it would be better to separate them in case one of them does not work out. If the implementation of A has no issues, but B is riddled with checkstyle errors, by giving each of them their own PRs, we can still implement and continue working on A while I fix the issues in B.

**Review by omupenguin — APPROVED** [review]

**Pull request merged**
